/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientrailway;

import java.awt.event.KeyEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Sharma's
 */
public class ChatWindow extends javax.swing.JFrame {

    /**
     * Creates new form ChatWindow
     */
    public ChatWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextPane12 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tf_complain_1 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        num_1 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tf_complain_3 = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tf_complain_4 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tf_complain_2 = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        tf_complain_5 = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        num_4 = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        num_2 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        num_5 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        num_3 = new javax.swing.JTextPane();
        tf_complain_no = new javax.swing.JTextField();
        send_complain_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jTextPane12.setEditable(false);
        jTextPane12.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jTextPane12.setText("INSTRUCTIONS!");
        jScrollPane12.setViewportView(jTextPane12);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 17)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("             \n          WELCOME TO THE COMPLAINTS FORUM!\n\n  If you are facing any issue in booking a ticket follow the \n  instructions given below.\n\n1.  Type the number corresponding to the query in the \n     field provided.\n\n2.  Click Send button to register your complaint within     \n     the system.\n\n3.  Try providing correct details wherever required to\n     avoid unnecessary issues.\n\n4.  Your complaints are registered into the database \n     along with your username and date. The Admin, then, \n     can see and provide the required solution.\n\n5.  Be patient! We provide efficient service to our \n     customers. The Admin will contact you as soon as \n     possible.\n         \n\n\n\tPress 'Back' button to exit !!");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 668));

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_complain_1.setEditable(false);
        tf_complain_1.setBackground(new java.awt.Color(255, 204, 204));
        tf_complain_1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tf_complain_1.setText("Payment done sucessfully but ticket not booked. ");
        jScrollPane2.setViewportView(tf_complain_1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 803, 45));

        num_1.setEditable(false);
        num_1.setBackground(new java.awt.Color(255, 153, 153));
        num_1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        num_1.setFont(new java.awt.Font("Arial Black", 1, 26)); // NOI18N
        num_1.setText("   1");
        jScrollPane6.setViewportView(num_1);

        jPanel2.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 34, 88, 44));

        tf_complain_3.setBackground(new java.awt.Color(255, 204, 204));
        tf_complain_3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tf_complain_3.setText("Payment Gateway is not responding.");
        jScrollPane3.setViewportView(tf_complain_3);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 803, 45));

        tf_complain_4.setEditable(false);
        tf_complain_4.setBackground(new java.awt.Color(255, 204, 204));
        tf_complain_4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tf_complain_4.setText("Ticket booked successfully but confirmation receipt is not shown.");
        jScrollPane4.setViewportView(tf_complain_4);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 803, 45));

        tf_complain_2.setEditable(false);
        tf_complain_2.setBackground(new java.awt.Color(255, 204, 204));
        tf_complain_2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        tf_complain_2.setText("Meal booked sucessfully but not delivered.");
        jScrollPane5.setViewportView(tf_complain_2);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 803, 45));

        tf_complain_5.setBackground(new java.awt.Color(255, 204, 204));
        tf_complain_5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 16)); // NOI18N
        tf_complain_5.setText("Other, Please specify");
        jScrollPane7.setViewportView(tf_complain_5);

        jPanel2.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 803, 45));

        num_4.setBackground(new java.awt.Color(255, 153, 153));
        num_4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        num_4.setText("   4");
        jScrollPane8.setViewportView(num_4);

        jPanel2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 246, 88, 44));

        num_2.setEditable(false);
        num_2.setBackground(new java.awt.Color(255, 153, 153));
        num_2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        num_2.setText("   2");
        jScrollPane9.setViewportView(num_2);

        jPanel2.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 104, 88, 44));

        num_5.setBackground(new java.awt.Color(255, 153, 153));
        num_5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        num_5.setText("   5");
        jScrollPane10.setViewportView(num_5);

        jPanel2.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 318, 88, 44));

        num_3.setEditable(false);
        num_3.setBackground(new java.awt.Color(255, 153, 153));
        num_3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        num_3.setText("   3");
        jScrollPane11.setViewportView(num_3);

        jPanel2.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 175, 88, 44));

        tf_complain_no.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 25)); // NOI18N
        tf_complain_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_complain_noActionPerformed(evt);
            }
        });
        tf_complain_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_complain_noKeyTyped(evt);
            }
        });
        jPanel2.add(tf_complain_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 297, 55));

        send_complain_button.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        send_complain_button.setText("SEND");
        send_complain_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_complain_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(send_complain_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 110, 55));

        back_button.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        back_button.setText("BACK");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(back_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 107, 42));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(465, 11, 980, 668));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_complain_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_complain_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_complain_noActionPerformed

    private void tf_complain_noKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_complain_noKeyTyped
        // TODO add your handling code here:
         char ch = evt.getKeyChar();
        if (!(Character.isDigit(ch) || (ch == KeyEvent.VK_BACK_SPACE) || ch == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_tf_complain_noKeyTyped

    private void send_complain_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_complain_buttonActionPerformed
        // TODO add your handling code here:
        String num=tf_complain_no.getText();
        int complain_num=Integer.parseInt(num);
        String complain_description="";
        if(complain_num>5||complain_num<1)
        {
            JOptionPane.showMessageDialog(this, "Please enter the correct complain number. Read instructions for more details!");
        }
        else
        {   
        int answer = JOptionPane.showConfirmDialog(null, "Do you want to Add?");
        if (answer == JOptionPane.YES_OPTION) {
            switch(complain_num)
            {
                case 1:
                    complain_description=tf_complain_1.getText();
                    break;
                case 2:
                    complain_description=tf_complain_2.getText();
                    break;
                case 3:
                    complain_description=tf_complain_3.getText();
                    break;
                case 4:
                    complain_description=tf_complain_4.getText();
                    break;
                case 5:
                    complain_description=tf_complain_5.getText();
                    if(complain_description.equals(""))
                    {
                        JOptionPane.showMessageDialog(this, "Complain description can not be null. Please specify your problem.");
                        
                    }
                    break;
                default:
                    break;
            }
            if(!complain_description.equals("")){
                long millis=System.currentTimeMillis();  
                java.sql.Date today_date=new java.sql.Date(millis);  
//                System.out.println(date); 
                String complain_username=Login.loggedInUser;
                Connection con=null;
                ResultSet rs=null;  
    final String classForName="com.mysql.cj.jdbc.Driver";
    final String getConnection = "jdbc:mysql://localhost:3306/Passenger";
    final String username="root";
    final String password="";
                int res=0;
                try
                {
//                    Class.forName(classForName);
//                    con = DriverManager.getConnection(getConnection, username,password);
//                    Statement insert_complain = con.createStatement();
//                    String query1 = "INSERT into complainbox(username, date_of_complain, complain_no,complain_description) VALUES('" + complain_username + "','" + today_date + "','" + complain_num + "','" + complain_description + "');";
//                    insert_complain.executeUpdate(query1);
//                    JOptionPane.showMessageDialog(this, "Your complain is sucessfully registered!Please wait until Admin contacts you.");
//                    tf_complain_no.setText("");
//                    tf_complain_5.setText("Other, Please specify");
                    
                    
                    Socket s = new Socket("localhost",6666);
                    DataOutputStream dout = new DataOutputStream(s.getOutputStream());

                    
                    dout.writeUTF("userComplaintRegistration");
                    dout.writeUTF(complain_username);
                    dout.writeUTF(num);
                    dout.writeUTF(complain_description);
                    dout.writeUTF("null");
                    dout.flush();

                    
                    DataInputStream din = new DataInputStream(s.getInputStream());
                    
                    res = din.read();
                    System.out.println("chatwindow res = "+res);
                    if(res==1)
                    {
                           JOptionPane.showMessageDialog(this,"Your complain is sucessfully registered!Please wait until Admin contacts you.");
                           tf_complain_5.setText("Other, Please Specify");
                           tf_complain_no.setText("");
                           
                    }
                    dout.close();
                    s.close();
                    
                    
                    
                }catch(Exception e)
                {
                    System.out.println(e);
                }
        }
        }
                
        
        
        }
        
    }//GEN-LAST:event_send_complain_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        Dashboarduser db=new Dashboarduser();
        db.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_back_buttonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane12;
    private javax.swing.JTextPane num_1;
    private javax.swing.JTextPane num_2;
    private javax.swing.JTextPane num_3;
    private javax.swing.JTextPane num_4;
    private javax.swing.JTextPane num_5;
    private javax.swing.JButton send_complain_button;
    private javax.swing.JTextPane tf_complain_1;
    private javax.swing.JTextPane tf_complain_2;
    private javax.swing.JTextPane tf_complain_3;
    private javax.swing.JTextPane tf_complain_4;
    private javax.swing.JTextPane tf_complain_5;
    private javax.swing.JTextField tf_complain_no;
    // End of variables declaration//GEN-END:variables
}
