/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientrailway;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.ObjectInputStream;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.util.Date; 
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.sql.rowset.CachedRowSet;

/**
 *
 * @author iayus
 */
public class Dashboarduser extends javax.swing.JFrame {

    /**
     * Creates new form Dashboarduser
     */
    public Dashboarduser() {
        initComponents();
        jLabel1.setText("Welcome  "+Login.loggedInUser+"");
        Toolkit toolkit = getToolkit();
        Dimension dim = toolkit.getScreenSize();
        setLocation(dim.width/2-getWidth()/2,dim.height/2-getHeight()/2); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        mealBooking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        jLabel1.setText("Welcome ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 450, 50));

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 120, 30));

        jButton2.setText("Change Password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 140));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Book a ticket");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 170, 30));

        jButton4.setText("Cancel booking");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 170, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel2.setText("Upcoming Tickets");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 330, 40));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Train no.", "Source", "Destination"
            }
        ));
        jScrollPane1.setViewportView(table1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 890, 140));

        jButton5.setText("Show");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 140, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(153, 255, 153));
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 130, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Get Train info");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));
        jPanel4.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 200, 100));

        mealBooking.setText("Book Meal");
        mealBooking.setMaximumSize(new java.awt.Dimension(119, 29));
        mealBooking.setMinimumSize(new java.awt.Dimension(119, 29));
        mealBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealBookingActionPerformed(evt);
            }
        });
        jPanel2.add(mealBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 170, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 960, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login.loggedInUser="";
        Login obj=new Login();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        
        try{
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Passenger", "root","");
//            PreparedStatement ps=con.prepareStatement("select * from passrecord where Username=?");
//            ps.setString(1, Login.loggedInUser);
//            ResultSet rs=ps.executeQuery();
            

            //ABHI CHANGING CODE HERE FOR SOCKET
            
            Socket s = new Socket("localhost",6666);
            DataOutputStream dout = new DataOutputStream(s.getOutputStream());
            
            
            dout.writeUTF("userDashboard");
            dout.writeUTF(Login.loggedInUser);
            
            dout.writeUTF("null");
            dout.flush();
            
            
            ObjectInputStream objectInput = new ObjectInputStream(s.getInputStream());
            CachedRowSet crs = (CachedRowSet)objectInput.readObject();
            
            dout.close();
            s.close();
            
            
            // TILL HERE ABHI IS CHANGING





            DefaultTableModel tm=(DefaultTableModel)table1.getModel();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Calendar calobj = Calendar.getInstance();
            SimpleDateFormat sdfo= new SimpleDateFormat("yyyy-MM-dd"); 
            Date cur=sdfo.parse(df.format(calobj.getTime()));
            while(crs.next())
            {
//                System.out.println(crs.getString("train_no"));
//                PreparedStatement ps1=con.prepareStatement("select * from train where train_no=?");
//                ps1.setString(1, rs.getString("train_no"));
//                ResultSet rs1=ps1.executeQuery();
                Date jour=sdfo.parse(crs.getString("DateOfJourney"));
//                if(jour.compareTo(cur)>=0)
//                {   
//                System.out.println(rs1.getString("StationFrom"));
                Object o[]={crs.getString("DateOfJourney"),crs.getString("train_no"),crs.getString("StationFrom"),crs.getString("StationTo")};
                tm.addRow(o);
//                }
            }
        }
        catch(Exception e) 
        {
            JOptionPane.showMessageDialog(this,e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Changepass obj=new Changepass();
                        obj.setVisible(true);
                        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
    boolean check(String s1)
    {
        int n=s1.length();
        for(int i=0;i<n;i++)
            if((int)s1.charAt(i)<48||(int)s1.charAt(i)>57)
                return true;
        return false;
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String s1=jTextField1.getText();
        if(s1.length()==0||check(s1))
        {
            jTextField1.setText("");
        }
        else
        {
            try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Passenger", "root","");
            String sql1 = "select * from train where train_no=?";
             int num=Integer.valueOf(s1);
            PreparedStatement pst1 = con.prepareStatement(sql1);
                    pst1.setString(1, s1);
                    ResultSet rs = pst1.executeQuery();
                    while(rs.next())
                    {
            JOptionPane.showMessageDialog(null, "Result for train no."+num+"\n"+"Name: "+rs.getString("name")+"\n"+"Source: "+
                    rs.getString("src")+"\n"+"Destination: "+rs.getString("dest"));    
                }
            }
        catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        jTextField1.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        TrainBetweenStation obj=new TrainBetweenStation();
        obj.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mealBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealBookingActionPerformed
        // TODO add your handling code here:
        OrderMeals orderMeal = new OrderMeals();
        orderMeal.setVisible(true);
        dispose();
    }//GEN-LAST:event_mealBookingActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Cancel cancel = new Cancel();
        cancel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton mealBooking;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
